### PR TITLE
makefile has to be added

### PR DESCRIPTION
**Pull request by noobieeeeeee**

### CODE REVIEW

**Comment by g-anupam** [comment]
image
Clang is just another comand for gcc. Nice Work, just the minor bug that you have to fix and you will be given the points

**Comment by g-anupam** [comment]
Ok i see you are going to upload a makefile for everything.
I have extended your timer by 30

**Comment by g-anupam** [comment]
Also on that note, once you are done close this PR and create a new PR to my File-Refactor branch instead of my main branch. If you have any doubts with it, while creating a PR at the top you will have the choice to select the branch you want to merge it to.

**Comment by noobieeeeeee** [comment]
Do I create a PR to the Code-Refactor branch? I do not see a File-Refactor branch @g-anupam

**Comment by g-anupam** [comment]
Yes correct a Code-Refactor branch. Also do comment the make command to run the file. Also are main.c and main1.c still required or have you just kept it for sake of preserving. You can answer all these in the new PR. Once the command for running is given and it runs smoothly i will assign you your points

**Pull request closed without merging**
