### PR TITLE
details can be entered into data.csv

### LINKED ISSUE #2: File Handling Fix
As of right now, the project uses a data.csv file to check which seats are booked, and assign seats accordingly.
However certain things you might observe when you inspect the code is that we are not writing onto data.csv for any new user created. Nor is the new booking saved onto it for future purchases.

To resolve the issue, kindly fix the code so that whenever a new user is created, it is appended onto data.csv, and a subsequent movie booking should be associated to that person.
Another thing to keep note of is that change should be permanent. It means that if a new user is created in one run of the code, even after exiting it and opening the next time, that seat should be booked and data.csv should have been appended.

### PR DESCRIPTION
**Pull request by jhalak-n**
Closes #2

### CODE REVIEW

**Comment by g-anupam** [comment]
I am looking into it

**Comment by g-anupam** [comment]
Ok so what i want from this issue is that suppose a person books a seat. Then it has to be added to data.csv. Now lets say i close the code and still run it again, it should be able to see previous bookings. So you will have to save it into data.csv and retrieve it from multiple runs of the code. If you can complete this i will go ahead and extend your time. If not please let me know

**Comment by jhalak-n** [comment]
@g-anupam made a PR. pls check.

**Comment by g-anupam** [comment]
Has bugs. So now the auditorium is not being printed when i am trying to book a seat. Directly asks for row and column.

**Comment by g-anupam** [comment]
Which Sem Hall Are you in

**Comment by jhalak-n** [comment]
semhall2

**Pull request closed without merging**
